// This file is auto-generated by nextjs-studio.
// Do not edit manually — re-run `npx nextjs-studio --generate-types` to update.

// Branded scalar types — structurally strings/numbers but semantically distinct.
declare const __brand: unique symbol;
type Brand<T, B extends string> = T & { readonly [__brand]: B };

export type Email     = Brand<string, 'Email'>;
export type HttpUrl   = Brand<string, 'HttpUrl'>;
export type ISODate   = Brand<string, 'ISODate'>;
export type MediaPath = Brand<string, 'MediaPath'>;
export type ID        = Brand<string, 'ID'>;
export type Slug      = Brand<string, 'Slug'>;

/** Data shape for the "agenda" collection. */
export interface AgendaEntry {
  titulo: string;
  slug: string;
  descricao: string;
  startsAt: Date;
  endsAt: Date;
  trilha: string;
  tipo: string;
  status: string;
  order: number;
}

/** Data shape for the "beneficios" collection. */
export interface BeneficiosEntry {
  icone: string;
  texto: string;
  order: number;
}

/** Data shape for the "chamadas" collection. */
export interface ChamadasEntry {
  chave: string;
  eyebrow: string;
  eyebrowTom: string;
  titulo: string;
  texto: string;
  ctaLabel: string;
  ctaUrl: HttpUrl;
  ctaVariante: string;
  order: number;
  prazoPrefixo: string;
}

/** Data shape for the "codigo-de-conduta" collection. */
export interface CodigoDeCondutaEntry Record<string, unknown>

/** Data shape for the "cotas" collection. */
export interface CotasEntry {
  nome: string;
  label: string;
  beneficios: Array<Record<string, unknown>>;
  featured: boolean;
  disponivel: boolean;
  order: number;
}

/** Data shape for the "ctf" collection. */
export interface CtfEntry {
  titulo: string;
  texto: string;
  formato: string;
  premiacao: string;
  linhas: Array<{
    kind: string;
    texto: string;
  }>;
  incluso: string;
}

/** Data shape for the "destaques" collection. */
export interface DestaquesEntry {
  chave: string;
  flag: string;
  eyebrow: string;
  titulo: string;
  texto: string;
}

/** Data shape for the "edicoes" collection. */
export interface EdicoesEntry {
  ano: number;
  tema: string;
  local: string;
  endereco: string;
  startsAt: Date;
  endsAt: Date;
  publico: string;
  resumo: string;
  albumUrl: string;
  status: string;
  foto: string;
}

/** Data shape for the "equipe" collection. */
export interface EquipeEntry {
  nome: string;
  slug: string;
  papel: string;
  url: HttpUrl;
  logo: string;
  order: number;
}

/** Data shape for the "faq" collection. */
export interface FaqEntry {
  pergunta: string;
  resposta: string;
  order: number;
}

/** Data shape for the "fatos" collection. */
export interface FatosEntry {
  valor: string;
  label: string;
}

/** Data shape for the "hero" collection. */
export interface HeroEntry {
  tituloLinha: string;
  tituloDestaque: string;
  lede: string;
  ctaPrimario: string;
  ctaSecundario: string;
  horario: string;
  lugares: Array<{
    nome: string;
  }>;
}

/** Data shape for the "imprensa" collection. */
export interface ImprensaEntry {
  veiculo: string;
  slug: string;
  titulo: string;
  url: HttpUrl;
  data: ISODate;
  tipo: string;
  trecho: string;
  logo: string;
  order: number;
}

/** Data shape for the "ingressos" collection. */
export interface IngressosEntry {
  nome: string;
  slug: string;
  lote: number;
  preco: number;
  parcelas: number;
  descricao: string;
  validThrough: Date;
  ctaUrl: HttpUrl;
  featured: boolean;
  order: number;
}

/** Data shape for the "links" collection. */
export interface LinksEntry Record<string, unknown>

/** Data shape for the "navegacao" collection. */
export interface NavegacaoEntry {
  label: string;
  href: string;
  secao: string;
  grupo: string;
  noMenu: boolean;
}

/** Data shape for the "palestrantes" collection. */
export interface PalestrantesEntry {
  nome: string;
  slug: string;
  cargo: string;
  resumo: string;
  experiencia: string;
  palestraTitulo: string;
  palestraResumo: string;
  temas: Array<{
    tema: string;
  }>;
  order: number;
  certificacoes: Array<{
    sigla: string;
  }>;
  palcos: Array<{
    nome: string;
  }>;
  cidade: string;
  empresa: string;
}

/** Data shape for the "parceiros" collection. */
export interface ParceirosEntry {
  nome: string;
  slug: string;
  url: HttpUrl;
  order: number;
}

/** Data shape for the "patrocinadores" collection. */
export interface PatrocinadoresEntry {
  nome: string;
  slug: string;
  logo: string;
  url: HttpUrl;
  cota: string;
  order: number;
}

/** Data shape for the "privacidade" collection. */
export interface PrivacidadeEntry {
  titulo: string;
  atualizadoEm: ISODate;
  lede: string;
  destaque: {
    titulo: string;
    texto: string;
  };
  blocos: Array<{
    titulo: string;
    texto: string;
  }>;
  oposicao: {
    titulo: string;
    texto: string;
    botaoDesligar: string;
    botaoLigar: string;
    estadoDesligado: string;
  };
}

/** Data shape for the "quiz" collection. */
export interface QuizEntry {
  slug: string;
  nome: string;
  sigla: string;
  time: string;
  timeCor: string;
  timeCorNome: string;
  timePapel: string;
  area: string;
  ferramenta: string;
  trilha: string;
  raridade: string;
  raridadeLabel: string;
  resumo: string;
  texto: string;
  noEvento: string;
  order: number;
  chave: string;
  enunciado: string;
  alternativas: Array<{
    chave: string;
    texto: string;
    pesos: {
      chave-de-fenda: number;
      arrombador-de-portas: number;
      faro-de-anomalia: number;
      radar-antecipado: number;
      cacador-de-bounty: number;
      perito-do-rastro: number;
      guardiao-da-norma: number;
      coruja-de-plantao: number;
      muralha-viva: number;
      guarda-do-codigo: number;
      escudo-de-crise: number;
      tradutor-de-risco: number;
      sombra-na-rede: number;
      pedreiro-de-pipeline: number;
      labia-de-acesso: number;
      cofre-de-segredos: number;
      isca-consciente: number;
      arbitro-do-simulado: number;
    };
  }>;
  eyebrow: string;
  titulo: string;
  lede: string;
  nomeLabel: string;
  nomePlaceholder: string;
  nomeAjuda: string;
  ctaComecar: string;
  ctaVoltar: string;
  ctaRefazer: string;
  progressoPrefixo: string;
  resultadoEyebrow: string;
  resultadoTimeLabel: string;
  resultadoCorLabel: string;
  resultadoAreaLabel: string;
  resultadoFerramentaLabel: string;
  resultadoSiglaLabel: string;
  resultadoRaridadeLabel: string;
  cartaLabel: string;
  cartaRodapeEsquerda: string;
  cartaRodapeDireita: string;
  fotoTrocar: string;
  verVerso: string;
  verFrente: string;
  fotoRemover: string;
  fotoAjuda: string;
  fotoAjustando: string;
  zoomLabel: string;
  recorteLabel: string;
  recorteBaixando: string;
  recorteProcessando: string;
  baixar: string;
  compartilhar: string;
  desafiar: string;
  desafiarCopiado: string;
  desafioTexto: string;
  compartilharTexto: string;
  gerando: string;
  erroExportar: string;
  avisoSafariTitulo: string;
  avisoSafariTexto: string;
  semJsTitulo: string;
  semJsTexto: string;
  indiceTitulo: string;
  indiceLede: string;
  ctaEvento: string;
  fechoTitulo: string;
  fechoTexto: string;
}

/** Data shape for the "secoes" collection. */
export interface SecoesEntry {
  chave: string;
  eyebrow: string;
  eyebrowTom: string;
  titulo: string;
  lede: string;
  nota: string;
  notaLinkLabel: string;
  notaLinkUrl: string;
  cta: string;
  ctaUrl: HttpUrl;
}

/** Data shape for the "settings" collection. */
export interface SettingsEntry {
  eventStartDate: Date;
  eventEndDate: Date;
  eventDisplayDate: string;
  venueName: string;
  venueAddress: string;
  venueMapUrl: HttpUrl;
  ticketsUrl: HttpUrl;
  volunteersDeadline: ISODate;
  cfpDeadline: string;
  sections: {
    fatos: boolean;
    sobre: boolean;
    edicoes: boolean;
    agenda: boolean;
    ctf: boolean;
    palestrantes: boolean;
    ingressos: boolean;
    participe: boolean;
    patrocinio: boolean;
    parceiros: boolean;
    local: boolean;
    faq: boolean;
    imprensa: boolean;
  };
}

/** Data shape for the "sobre" collection. */
export interface SobreEntry {
  titulo: string;
  texto: string;
  origemTitulo: string;
  origemTexto: string;
  pilares: Array<Record<string, unknown>>;
}

// Augment both entry points so queryCollection() is fully typed regardless of import path.
declare module 'nextjs-studio' {
  interface CollectionTypeMap {
    "agenda": AgendaEntry;
    "beneficios": BeneficiosEntry;
    "chamadas": ChamadasEntry;
    "codigo-de-conduta": CodigoDeCondutaEntry;
    "cotas": CotasEntry;
    "ctf": CtfEntry;
    "destaques": DestaquesEntry;
    "edicoes": EdicoesEntry;
    "equipe": EquipeEntry;
    "faq": FaqEntry;
    "fatos": FatosEntry;
    "hero": HeroEntry;
    "imprensa": ImprensaEntry;
    "ingressos": IngressosEntry;
    "links": LinksEntry;
    "navegacao": NavegacaoEntry;
    "palestrantes": PalestrantesEntry;
    "parceiros": ParceirosEntry;
    "patrocinadores": PatrocinadoresEntry;
    "privacidade": PrivacidadeEntry;
    "quiz": QuizEntry;
    "secoes": SecoesEntry;
    "settings": SettingsEntry;
    "sobre": SobreEntry;
  }
}
declare module 'nextjs-studio/server' {
  interface CollectionTypeMap {
    "agenda": AgendaEntry;
    "beneficios": BeneficiosEntry;
    "chamadas": ChamadasEntry;
    "codigo-de-conduta": CodigoDeCondutaEntry;
    "cotas": CotasEntry;
    "ctf": CtfEntry;
    "destaques": DestaquesEntry;
    "edicoes": EdicoesEntry;
    "equipe": EquipeEntry;
    "faq": FaqEntry;
    "fatos": FatosEntry;
    "hero": HeroEntry;
    "imprensa": ImprensaEntry;
    "ingressos": IngressosEntry;
    "links": LinksEntry;
    "navegacao": NavegacaoEntry;
    "palestrantes": PalestrantesEntry;
    "parceiros": ParceirosEntry;
    "patrocinadores": PatrocinadoresEntry;
    "privacidade": PrivacidadeEntry;
    "quiz": QuizEntry;
    "secoes": SecoesEntry;
    "settings": SettingsEntry;
    "sobre": SobreEntry;
  }
}
